[project]
name = "analytics-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clickhouse-driver>=0.2.9",
    "fastapi[standard]>=0.115.11",
]
