name: Monorepo Hello World CI

on:
  push:
    branches: 
      - main
      - DevOps_Onboarding 
  pull_request:
    branches: 
      - main
      - DevOps_Onboarding

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      dashboard: ${{ steps.filter.outputs.dashboard }}
      server: ${{ steps.filter.outputs.server }}
      react-form: ${{ steps.filter.outputs.react-form }}
    steps:
    - uses: actions/checkout@v3
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dashboard:
            - 'Analytics-Dashboard/**'
          server:
            - 'Analytics-Server/**'
          react-form:
            - 'React-Form-Analytics/**'

  hello-dashboard:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.dashboard == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Hello World for Dashboard
      run: |
        echo "Hello World from Analytics Dashboard!"
        ls Analytics-Dashboard
        echo "Current directory contents:"
        pwd

  hello-server:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Hello World for Server
      run: |
        echo "Hello World from Analytics Server!"
        ls Analytics-Server
        echo "Current directory contents:"
        pwd

  hello-react-form:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.react-form == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Hello World for React Form Analytics
      run: |
        echo "Hello World from React Form Analytics!"
        ls React-Form-Analytics
        echo "Current directory contents:"
        pwd

  hello-all:
    if: ${{ always() }}
    needs: [hello-dashboard, hello-server, hello-react-form]
    runs-on: ubuntu-latest
    steps:
    - name: Final Hello World
      run: echo "Workflow complete for all services!"