name: Service Workflow Template

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      service-name:
        required: true
        type: string
      dockerfile-path:
        required: false
        type: string
        default: Dockerfile

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.service-path }}
        file: ${{ inputs.service-path }}/${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ inputs.service-name }}:latest
    
    - name: Verify Docker Image Details
      run: |
        echo "Image pushed to GitHub Container Registry"
        echo "Service Name: ${{ inputs.service-name }}"
        echo "Repository Owner: ${{ github.repository_owner }}"
        echo "Image Tag: latest"