name: Service Workflow Template

on:
  workflow_call:
    inputs:
      service-path:
        required: true
        type: string
      service-name:
        required: true
        type: string

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Hello World for ${{ inputs.service-name }}
      run: |
        echo "Hello World from ${{ inputs.service-name }}!"
        echo "Current Branch: ${{ github.ref_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Service Path: ${{ inputs.service-path }}"
        echo "Current Working Directory:"
        pwd
        echo "Contents of Service Directory:"
        ls -la ${{ inputs.service-path }}